<?php
function drupaltonetsuite_help() {

}

/*
* Implementing hook_menu()
*/

function drupaltonetsuite_menu() {
  $items = array();
  $items['drupaltonetsuite'] = array(
    'title' => t('DrupalToNetsuite'),
    'position' => 'left',
    'page callback' => 'drupaltonetsuite_all',
    'access arguments' => array('access netsuitetodrupal'),
    'description' => t('Main D2N Page'),
    'type' => MENU_NORMAL_ITEM,
    );
  $items['drupaltonetsuite/form'] = array(
    'title' => t('Create new Lead'),
    'position' => 'left',
    'page callback' => 'drupaltonetsuite_form',
    'access arguments' => array('access netsuitetodrupal'),
    'description' => t('Create a new Lead'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/settings/drupaltonetsuite'] = array(
    'title' => 'DrupalToNetsuite',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupaltonetsuite_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'drupaltonetsuite.admin.inc',
    );
  return $items;
}

/*
*Implementing hook_perm()
*/

function drupaltonetsuite_perm() {
	return array( 'access netsuitetodrupal' , 'administer netsuitetodrupal');
}

/*
 * Implementing hook_path()
 */
 function drupaltonetsuite_path() {
   if (function_exists('drupal_get_path')) {
    // Let drupal set the path
    $path = drupal_get_path('module', 'drupaltonetsuite');
  }
  else {
    // Fallback to trying to find the path based on PHP's knowledge of our
    // current path.
    $path = dirname(__FILE__);
  }
  return $path;
 }
 
/*
 *Implementing hook_form()
 */
function drupaltonetsuite_form() {
  return drupal_get_form('drupaltonetsuite_my_form');
}

/*
 * Creating the Leads Form, TODO: Let the admin create this form using formbuilder
 */

function drupaltonetsuite_my_form($form_state) {
  $form['name'] = array(
    '#type' => 'fieldset',
    '#title' => t('Personal Details'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    );
    $form['name']['first'] = array(
    '#type' => 'textfield',
    '#title' => t('First Name'),
    '#required' => TRUE,
    '#description' => t('Please your First Name'),
    '#size' => 20,
    '#maxlength' => 20,
    );
    $form['name']['last'] = array(
    '#type' => 'textfield',
    '#title' => t('LastName'),
    '#required' => TRUE,
    '#description' => t('Please Enter yout Last Name'),
    '#size' => 20,
    '#maxlength' => 20,
    );
    $form['name']['email'] = array (
    '#type' => 'textfield',
    '#title' => t('Email ID'),
    '#required' => TRUE,
    '#description' => t('Please Enter your email address'),
    '#size' => 20,
    );
    $form['name']['phone'] = array (
    '#type' => 'textfield',
    '#title' => t('Phone No'),
    '#required' => TRUE,
    '#description' => t('Please enter your PhoneNO'),
    '#size' => 20,
    '#maxlength' => 10,
    );
    $form['company'] = array(
    '#type' => 'fieldset',
    '#title' => t('Company Details'),
    '#collapsible' => TRUE,
    '#collasped' => FALSE,
    );
    $form['company']['company_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Company Name'),
    '#required' => TRUE,
    '#description' => t('Please enter your Company Name'),
    '#size' => 20,
    '#maxlength' => 20,
    );
    $form['company']['address'] = array(
    '#type' => 'textarea',
    '#title' => t('Company Address'),
    '#description' => t('Please enter your Company Address'),
    '#size' => 5,
    );
    $form['company']['country'] = array (
    '#type' => 'textfield',
    '#title' => t('Country'),
    '#description' => t('Please enter you Country Name'),
    '#size' => 20,
    );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  $form['reset'] = array(
  '#type' => 'submit',
  '#value' => 'Reset Form',
  '#validate' => array('drupaltonetsuite_my_form_validate'),
  );
  return $form;
  
}

/*
 * Reseting the Leads Form
 */

function drupaltonetsuite_my_form_clear($form, &$form_state) {
    $form_state['rebuild'] = TRUE;
}

//Form Validation
 function drupaltonetsuite_my_form_validate($form, &$form_state) {
  $first_name = $form_state['values']['first'];
  $last_name = $form_state['values']['last'];
  $year_of_birth = $form_state['values']['dob'];
  if (!$first_name)
  form_set_error('first' , 'Please enter First Name');
  if (!$last_name)
  form_set_error('last', 'Please Enter Last Name');
  if ($year_of_birth && ($year_of_birth < 1900 || $year_of_birth > 2010)) {
    form_set_error('dob', 'Enter a year between 1900 and 2010.');
  }
  }
/*
 * TODO: Post data to Netsuite from the Form
 */
  
function drupaltonetsuite_my_form_submit($form, &$form_state) {
	//$first_name = $form_state['values']['first'];
	//$last_name = $form_state['values']['last'];
	//$dob = $form_state['values']['dob'];
    //drupal_set_message(t('The form has been submitted.<br>FirstName is:').$first_name.t('<br>LastName is: ').$last_name);
    	include_once (drupaltonetsuite_path().'/PHPtoolkit.inc');
    	$myNSclient = new nsClient( nsHost::live );
	$email = "spuvala@argusoft.com";
	$password = "argusadmin!";
	$account = "TSTDRV658597";
	$role = "3";

	// set request level credentials. (email, password, account#, internal id of role)
	$myNSclient->setPassport($email, $password, $account, $role);

	//include_once (drupaltonetsuite_path().'/login_info.inc');
	$customerFields = array (
		'isPerson'		=> false,
		'firstName'		=> $form_state['values']['first'],
		'lastName'		=> $form_state['values']['last'],
		'companyName'		=> $form_state['values']['company_name'],
		'phone'			=> $form_state['values']['phone'],
		'email'			=> $form_state['values']['email'],
		//'country' 		=> $form_state['values']['country'],
		'giveAccess'		=> false,
		'entityStatus'         => array('internalId' => '6'),
	);
	// create Customer record
	$customer = new nsComplexObject('Customer');
	// set fields
	$customer->setFields($customerFields);
	// perform add operation and store nsWriteResponse object in $addResponse variable 
	$addResponse = $myNSclient->add($customer);
	// handle add response
	if (!$addResponse->isSuccess) {
		echo "Lead couldnot be added in netsuite. Error: " .$addResponse->statusDetail[0]->message;		
	} else {
		echo "Lead has been successfully added";
	}
}  
/*
 * Creating a netsuite page with all the features available to the admin
 */

function drupaltonetsuite_all() {
global $base_url;
	$message = "This module lets the you integrate netsuite with drupal<br>It provides basic functionality such a creating leads,assigning territories,adding sales representatives<br><a href=".$base_url."/drupaltonetsuite/form>Create a New Lead</a>";
	return $message;
}